"""Initial migration: create tickets, tags, and ticket_tags tables

Revision ID: 55edc2c3852c
Revises:
Create Date: 2026-01-11 09:26:49.978664

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55edc2c3852c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('open', 'completed')", name="check_ticket_status"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ticket_tags",
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("ticket_id", "tag_id"),
    )
    # ### end Alembic commands ###

    # Create indexes
    op.create_index("idx_tickets_status", "tickets", ["status"])
    op.create_index("idx_tickets_title", "tickets", ["title"])
    op.create_index(
        "idx_tickets_created_at",
        "tickets",
        ["created_at"],
        postgresql_using="btree",
        postgresql_ops={"created_at": "DESC"},
    )
    op.create_index("idx_ticket_tags_tag_id", "ticket_tags", ["tag_id"])

    # Create trigger functions
    op.execute(
        """
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """
    )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION update_completed_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
            -- 当状态变为 completed 时，设置完成时间
            IF NEW.status = 'completed' AND (OLD.status IS NULL OR OLD.status != 'completed') THEN
                NEW.completed_at = NOW();
            -- 当状态从 completed 变为其他状态时，清空完成时间
            ELSIF NEW.status != 'completed' AND OLD.status = 'completed' THEN
                NEW.completed_at = NULL;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """
    )

    # Create triggers
    op.execute(
        """
        CREATE TRIGGER trigger_tickets_updated_at
            BEFORE UPDATE ON tickets
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
    """
    )

    op.execute(
        """
        CREATE TRIGGER trigger_tickets_completed_at
            BEFORE UPDATE ON tickets
            FOR EACH ROW
            EXECUTE FUNCTION update_completed_at_column();
    """
    )

    op.execute(
        """
        CREATE TRIGGER trigger_tags_updated_at
            BEFORE UPDATE ON tags
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
    """
    )


def downgrade() -> None:
    # Drop triggers
    op.execute("DROP TRIGGER IF EXISTS trigger_tags_updated_at ON tags;")
    op.execute("DROP TRIGGER IF EXISTS trigger_tickets_completed_at ON tickets;")
    op.execute("DROP TRIGGER IF EXISTS trigger_tickets_updated_at ON tickets;")

    # Drop trigger functions
    op.execute("DROP FUNCTION IF EXISTS update_completed_at_column();")
    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column();")

    # Drop indexes
    op.drop_index("idx_ticket_tags_tag_id", table_name="ticket_tags")
    op.drop_index("idx_tickets_created_at", table_name="tickets")
    op.drop_index("idx_tickets_title", table_name="tickets")
    op.drop_index("idx_tickets_status", table_name="tickets")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ticket_tags")
    op.drop_table("tickets")
    op.drop_table("tags")
    # ### end Alembic commands ###
